/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FindNumber;

public class App {

    private static final String GAME_HEADER = "Find a Number between 0 and 120!";

    public static void game() {
        System.out.println("Game over!");
    }

    public static void main(String[] args) {
        System.out.println(GAME_HEADER);
        game();
    }
}